---
# UI / User Credentials (Kept for manual admin access)
#stalwart_admin_user: "admin"
#stalwart_admin_password: "your_secure_bootstrap_password"

# Automation API Token (Used exclusively by Ansible & Systemd)
stalwart_api_token: "API_AABC"

stalwart_cli_path: "/root/.cargo/bin/stalwart-cli"

stalwart_domains:
  - name: "domain.site"
    state: "present"
    dns: "hetzner"

  - name: "www2.domain.site"
    state: "absent"

  - name: "mail.domain.site"
    state: "present"
    dns: "hetzner"

  - name: "stwrt.domain.online"
    state: "present"
    dns: "spaceship"


caddy_domains:
  - name: "www.domain.site"
    state: "present"
    dns: "hetzner"
    caddy:
      - "respond \"Hello World\" 200"

  - name: "nomail.domain.site"
    state: "absent"
    dns: "hetzner"
    caddy:
      - "reverse_proxy 127.0.0.1:4443"




dns_key_map:
  hetzner: "FOOBAR"
  spaceship:
    api_key: "BAZ"
    api_secret: "QUUX"


# --- ACME Endpoint Config ---
# You can flip this to any custom CA endpoint string
# acme_directory_url: "https://acme-staging-v02.api.letsencrypt.org/directory"
acme_directory_url: "https://acme-v02.api.letsencrypt.org/directory"


# Custom systemd Service Overrides for Caddy, only for the /usr/local/ path
caddy_service_override_lines: |
  ExecStart=
  ExecStart=/usr/local/bin/caddy run --environ --config /etc/caddy/Caddyfile
  ExecReload=
  ExecReload=/usr/local/bin/caddy reload  --config /etc/caddy/Caddyfile
