---
- name: Reload Systemd Daemon
  systemd:
    daemon_reload: true

- name: Restart Caddy
  service:
    name: caddy
    state: restarted

- name: Reload Caddy
  service:
    name: caddy
    state: reloaded
